---
abstract: 'Authenticate using the Yubico Web API'
author:
  - 'Chisel <chisel@chizography.net>'
build_requires:
  Test::UseAllModules: 0
  strict: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Auth-YubiKey-Client-Web
requires:
  Carp: 0
  Digest::HMAC_SHA1: 0
  HTTP::Tiny: 0
  MIME::Base64: 0
  Moo: 0
  URI::Escape: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Auth-YubiKey-Client-Web
  repository: git://github.com/chiselwright/auth-yubikey-client-web.git
version: 0.0.1
